### ISSUE TITLE
Issue after upgrading to Spree 3.3.0

### ISSUE THREAD

**Issue by Dragsbaek** [QuintinAdam/spree_flexi_variants#13]
Getting

```
NoMethodError (undefined method 'with_indifferent_access' for #<ActionController::Parameters:0x007faacb5207b0>):

actionpack (5.1.4) lib/action_controller/metal/strong_parameters.rb:235:in 'initialize'
/Users/thomas/.rvm/gems/ruby-2.3.1/bundler/gems/spree_flexi_variants-db0855e9d9d4/app/models/spree/order_contents_decorator.rb:13:in 'new'
/Users/thomas/.rvm/gems/ruby-2.3.1/bundler/gems/spree_flexi_variants-db0855e9d9d4/app/models/spree/order_contents_decorator.rb:13:in 'add_to_line_item'
spree_core (3.3.2) app/models/spree/order_contents.rb:11:in 'add'
spree_frontend (3.3.2) app/controllers/spree/orders_controller.rb:51:in 'populate'

```
When adding product to cart in spree 3.3

**Comment by gbrlcustodio** [comment]
@Dragsbaek, have you figured out how to fix it?

**Comment by Dragsbaek** [comment]
nope:/

**Comment by gbrlcustodio** [comment]
Can you try this out https://github.com/gcmartins93/spree_flexi_variants. I've tried on my personal project and it worked. I'll pull request it later.

**Comment by Dragsbaek** [comment]
Sweet! Thanks man:)

**Comment by QuintinAdam** [comment]
Changes are now in master or branch spree-3-3
